import { GitHubPublisher } from "./github.js";

const STORAGE={token:"subtleResolveAdminToken",repository:"subtleResolveAdminRepository",branch:"subtleResolveAdminBranch"};
const $=id=>document.getElementById(id); const state={repo:null,files:{}};
$("repository").value=localStorage.getItem(STORAGE.repository)||$("repository").value; $("branch").value=localStorage.getItem(STORAGE.branch)||$("branch").value;
$("connect-form").addEventListener("submit",async event=>{event.preventDefault();const credentials={repository:$("repository").value.trim(),branch:$("branch").value.trim(),token:$("token").value.trim()};$("connect-message").textContent="Checking repository access…";try{state.repo=new GitHubPublisher(credentials);await state.repo.verify();await load();localStorage.setItem(STORAGE.repository,state.repo.repository);localStorage.setItem(STORAGE.branch,state.repo.branch);if($("remember").checked)localStorage.setItem(STORAGE.token,credentials.token);else localStorage.removeItem(STORAGE.token);sessionStorage.setItem(STORAGE.token,credentials.token);$("connect").hidden=true;$("manager").hidden=false;$("connect-message").textContent="";}catch(error){$("connect-message").textContent=error.message||"Unable to connect.";}});
$("reload").addEventListener("click",()=>load()); $("publish").addEventListener("click",publish);
async function load(){if(!state.repo)return;$("save-message").textContent="Loading repository data…";try{const [catalogue,releases,latest,repositories,external,tags]=await Promise.all([state.repo.getText("site/catalogue.json"),state.repo.getText("data/catalogue-releases.json"),state.repo.getText("data/latest-update.json"),state.repo.getText("data/repositories.csv"),state.repo.getText("data/external-tools.md"),state.repo.getText("data/search-tags.json")]);state.files={repositories,external,tags};const c=JSON.parse(catalogue),r=JSON.parse(releases),u=JSON.parse(latest);$("repo-label").textContent=`${state.repo.repository} · ${state.repo.branch}`;$("freshness").textContent=`Latest catalogue release ${u.release||"unknown"} · ${u.added_urls?.length||0} new resources · checked ${u.date||"unknown"}`;$("stats").innerHTML=[[c.entries?.length||0,"Catalogue resources"],[c.entries?.filter(e=>e.origin==="github").length||0,"GitHub entries"],[c.entries?.filter(e=>e.origin==="external").length||0,"External entries"],[r.releases?.length||0,"Catalogue releases"]].map(([n,l])=>`<div class="stat"><strong>${n}</strong><span>${l}</span></div>`).join("");$("repositories").value=repositories;$("external").value=external;$("tags").value=tags;const base=`https://github.com/${state.repo.repository}`;$("site-link").href="https://subtlesayak.github.io/subtle-resolve-list/";$("releases-link").href=`${base}/releases`;$("actions-link").href=`${base}/actions`;$("source-link").href=base;$("save-message").textContent="Loaded. Review changes before publishing.";}catch(error){$("save-message").textContent=error.message||"Unable to load catalogue data.";}}
async function publish(){const files=[{path:"data/repositories.csv",content:$("repositories").value.trimEnd()+"\n"},{path:"data/external-tools.md",content:$("external").value.trimEnd()+"\n"},{path:"data/search-tags.json",content:$("tags").value.trimEnd()+"\n"}];try{JSON.parse($("tags").value);JSON.parse(await state.repo.getText("site/catalogue.json"));}catch{ $("save-message").textContent="Search tags must be valid JSON before publishing.";return;}$("publish").disabled=true;$("save-message").textContent="Publishing atomic source-data commit…";try{const commit=await state.repo.publish(files,"Admin: update Resolve List source data");$("save-message").textContent=`Published ${commit.sha.slice(0,7)}. The repository validation and Pages workflow will run next.`;await load();}catch(error){$("save-message").textContent=error.message||"Publishing failed.";}finally{$("publish").disabled=false;}}
